name: python CI/CD pipeline

on: [push]

jobs:
  test:
    name: Test Script
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Run Script
          run: py ./hello.py
  build:
    name: Build and Store Artifact
    runs-on: ubuntu-latest
    needs: [test]
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Create Artifact
          uses: actions/upload-artifact@v3
          with:
            name: python_cicd_pipeline
            path: ./